name: daily plot update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Timestamp
        run: |
          file="timestamp.txt"
          if [ -f "$file" ] ; then
          rm "$file"
          fi
          date >> "$file"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Scheduled update of plots
            
            [skip-checks]
          file_pattern: 'shared/*'
          disable_globbing: true