name: daily plot update

on:
  workflow_dispatch:

  schedule:
    - cron: '30 0 * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Timestamp and Add Plots
        run: |
          file="shared/timestamp.txt"
          if [ -f "$file" ]; then
            rm "$file"
          fi
          date >> "$file"
          git add shared

      - name: Show Diff
        run: git diff

      - name: List Contents
        run: ls -lR shared

      - name: Show Status Plus Untracked
        run: git status --untracked-files=all

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Scheduled update of plots
            
            
            [skip-checks]
          file_pattern: 'shared/**'
          push_options: '--force-with-lease'