name: daily plot update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.IDK_SECRET }}'

      - name: Mark time
        run: |
          date >> shared/timestamp.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Scheduled update of plots'
          file_pattern: 'shared/*'
