name: daily plot update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  - format-code:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - uses: actions/checkout@v4
          with:
            token: '${{ secrets.IDK_SECRET }}'

        - name: Git Auto Commit
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: 'Scheduled update of plots'
            file_pattern: '*.html'
            repository: 'shared'

        - name: Push Changes
          env:
            PAT: '${{ secrets.IDK_SECRET }}'
          run: |
            git push https://x-access-token:${PAT}@github.com/${{ github.repository }}


